# Git sync
dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/xotlr92/investment.git
    branch: main
    rev: HEAD
    depth: 1
    subPath: ""